### ISSUE TITLE
针对 PC WeChat 3.2.1.154 失效

### ISSUE THREAD

**Issue by LuohuaRain** [nulastudio/pic2meme#1]
![image](https://user-images.githubusercontent.com/37979368/118125180-39b8c000-b429-11eb-96a9-aeec3aed7369.png)

**Comment by liesauer** [comment]
发送之后也还是文件吗？
你这个特定版本是属于旧版还是新版？
有表情包源文件吗？

**Comment by LuohuaRain** [comment]
文件为<img width="520" alt="raycast-untitled (2)" src="https://user-images.githubusercontent.com/37979368/118350005-f3797300-b586-11eb-9900-6b83317ee7ae.png">

**Comment by liesauer** [comment]
好的，我测试一下

**Comment by liesauer** [comment]
fixed in f6ceba8cd23a58c4276e0f7d74e13a2ed3225bd8
