### ISSUE TITLE
最新版本问题复制到剪贴板失败

### ISSUE THREAD

**Issue by FellBan** [nulastudio/pic2meme#3]
复制到剪贴板失败
1 2 模式都试过了

什么时候可以让网络图片变微信表情包的就好了
![111](https://user-images.githubusercontent.com/13709020/168408499-f7f81b10-2738-407e-90f2-a8effac82d43.jpg)

**Comment by liesauer** [comment]
网络图片是支持转换的，没法转换要具体看下啥情况才行（可能是网站开启了防盗链），能不能提供下以下信息：
1. 什么链接？
2. 哪张图片？
3. 你是怎么复制的？（比如右键复制图片、选中然后Ctrl+C、等等）

**Comment by FellBan** [comment]
> 网络图片是支持转换的，没法转换要具体看下啥情况才行（可能是网站开启了防盗链），能不能提供下以下信息：
> 
> 1. 什么链接？
> 2. 哪张图片？
> 3. 你是怎么复制的？（比如右键复制图片、选中然后Ctrl+C、等等）

我这个是QQ群里拉进去的 然后我看复制到剪贴板失败   保存本地也是 复制到剪贴板失败

**Comment by liesauer** [comment]
有具体的图片文件嘛？

**Comment by FellBan** [comment]
上面放的那张就是




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nulastudio/pic2meme"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月14日(星期六) 中午11:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nulastudio/pic2meme] 最新版本问题复制到剪贴板失败 (Issue #3)





 
网络图片是支持转换的，没法转换要具体看下啥情况才行（可能是网站开启了防盗链），能不能提供下以下信息：
  
什么链接？
 
哪张图片？
 
你是怎么复制的？（比如右键复制图片、选中然后Ctrl+C、等等）

**Comment by liesauer** [comment]
我试了下是可以的，还有原文件嘛？试下将qq直接保存的图片打包成zip上传，有可能直接上传github后被转换了

![image](https://user-images.githubusercontent.com/8676741/168408897-461e7e9d-46c7-4ffd-b080-06824db5f89a.png)

**Comment by FellBan** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nulastudio/pic2meme"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月14日(星期六) 中午11:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nulastudio/pic2meme] 最新版本问题复制到剪贴板失败 (Issue #3)





 
我试了下是可以的，还有原文件嘛？试下将qq直接保存的图片打包成zip上传，有可能直接上传github后被转换了

**Comment by liesauer** [comment]
github好像没办法识别邮件里的附件的

**Comment by FellBan** [comment]
> github好像没办法识别邮件里的附件的

[111.zip](https://github.com/nulastudio/pic2meme/files/8692061/111.zip)

**Comment by liesauer** [comment]
我试了下也是可以的，你是下载的Releases里的最新版？

**Comment by FellBan** [comment]
> 我试了下也是可以的，你是下载的Releases里的最新版？

![image](https://user-images.githubusercontent.com/13709020/168409168-d3a98301-b9ea-409f-a806-91a0b577e077.png)
不知道为啥。我试试看老版本

**Comment by liesauer** [comment]
晚上我生成个Debug版本的给你，看下具体报错是啥，有可能是杀毒软件给拦截了剪贴板。

**Comment by FellBan** [comment]
> 晚上我生成个Debug版本的给你，看下具体报错是啥，有可能是杀毒软件给拦截了剪贴板。

没开任何杀软   公司电脑  回家试试看我自己的电脑看看

**Comment by liesauer** [comment]
可以试下这个版本，看下报什么错

[Debug.zip](https://github.com/nulastudio/pic2meme/files/8692849/Debug.zip)

**Comment by FellBan** [comment]
> 可以试下这个版本，看下报什么错
> 
> [Debug.zip](https://github.com/nulastudio/pic2meme/files/8692849/Debug.zip)

![image](https://user-images.githubusercontent.com/13709020/168455583-de3e272e-8e96-49f4-ad2d-3e12d350e9c8.png)
不好意思现在才回复

**Comment by liesauer** [comment]
这个报错是因为被不知道什么程序占用了剪贴板，所以粘贴失败。

**Comment by FellBan** [comment]
> 这个报错是因为被不知道什么程序占用了剪贴板，所以粘贴失败。

那我自行排查一下
