### ISSUE TITLE
powershell无法运行fix_config.ps1脚本

### ISSUE THREAD

**Issue by squall1027** [nulastudio/pic2meme#4]
如附件所示
![image](https://user-images.githubusercontent.com/35394311/208453997-eb3ca92e-9285-439d-aae2-159f3dc5c1bc.png)
![image](https://user-images.githubusercontent.com/35394311/208455076-688eebd4-3806-4207-b395-37693b7af84a.png)

請問如何解決? 謝謝 -

**Comment by squall1027** [comment]
> 這是由於你的系統不允許執行powershell腳本，請嘗試以下解決方法：
> 
> 1. 管理員權限打開powershell終端
> 2. 運行`Set-ExecutionPolicy Bypass`
> 3. 重啟VS，再試試譯

我嘗試過了，情況依舊😂
我換了另一台PC也有這個情況
![image](https://user-images.githubusercontent.com/35394311/208634864-984b39c9-44f4-44e7-8a8f-9d129809d11b.png)

**Comment by liesauer** [comment]
试下在VS里的powershell查看和设置，我怀疑VS用的不是用一个策略。
![image](https://user-images.githubusercontent.com/8676741/208635944-d1420d1a-2fa4-40e7-ae34-aaa9469d6e0e.png)

**Comment by liesauer** [comment]
使用以下命令查看所有策略，`Get-ExecutionPolicy -List`
